---
title: "Midterm notebook"
output: html_notebook
---


# Section 1

```{r}
library(rstan)

model_code <- "
data {
  int<lower=0> J;
  real y[J];
  real<lower=0> sigma[J];
}

parameters {
  real mu;
  real<lower=0> tau;
  real theta[J];
}

model {
  mu ~ normal(0, 5);
  tau ~ cauchy(0, 5);
  theta ~ normal(mu, tau);
  y ~ normal(theta, sigma);
}
"
schools_dat <- list(J = 8, 
                    y = c(28,  8, -3,  7, -1,  1, 18, 12),
                    sigma = c(15, 10, 16, 11,  9, 11, 10, 18))
fit1 <- stan(model_code = model_code, 
              data=schools_dat, 
              seed=483892929, 
             iter = 1000)
```

```{r}
fit1
```

```{r}
plot(fit1, plotfun ="trace")
```

```{r}
plot(fit1, plotfun = "ac")
```

# Section 2

```{r}
library(brms)
df <- data.frame(tests = 5,
                 score = c(3,2,0,1,3,4,5,4), 
                 p = 1,
                 subject = c("p1", "p2", "p3", "p4",
                           "p5", "p6", "p7", "p8"))
fit2 <- brm(score | trials(tests) ~ p - 1,
           data = df,
           family = binomial(link = "identity"),
           prior = prior(beta(1, 1), lb=0, ub=1))
```

```{r}
fit2
```

```{r}
library(tidyverse)
library(bayestestR)
posterior <- posterior_samples(fit2) %>% 
  select("b_p")
posterior
```

```{r}
#find minimum, maximum, mean, and sd
posterior %>% 
  summarise(...)
```

```{r}
hdi(...)
```

```{r}
equivalence_test(...)
```

